### ISSUE TITLE
Aufräge/Positionen/ Budgetübersicht

### ISSUE THREAD

**Issue by jamoksarita** [puzzle/puzzletime#10]
Wenn in einem Auftrag eine nichtverrechenbare Position erfasst wird, wird diese zum "Budget Total" hinzugerechnet. Es wäre cool wenn das Budgettotal inkl. und exkl. verrechenbaren Positionen angezigt würde.

**Comment by Joshuasony** [comment]
In diesem Zusammenhang fände ich es auch toll, wenn man das schneller sehen würde. In einer Liste von 100 Einträgen verrechenbar und 1 Eintrag nicht verrechenbar möchte ich sofort sehen, ob es nicht verrechenbare Buchungen gibt. 
Dies könnte man entweder in der Tabelle hervorheben
![grafik](https://user-images.githubusercontent.com/7139459/49589471-c8c47280-f969-11e8-8371-02b5ab79638b.png)

oder im Spaltentitel:
![grafik](https://user-images.githubusercontent.com/7139459/49589511-e09bf680-f969-11e8-93b3-d81520a97e1f.png)

oder mit einem Status Kreis welcher nur erscheint, wenn es nicht verrechenbare Buchungen gibt:
![grafik](https://user-images.githubusercontent.com/7139459/49589885-cdd5f180-f96a-11e8-9f93-c02cbf130619.png)


oder halt "versteckt" aber mit einem Klick die Anzahl ersichtlich neben der Option im Dropdown:
![grafik](https://user-images.githubusercontent.com/7139459/49589705-586a2100-f96a-11e8-8a65-39360a94d995.png)

**Comment by odaner** [comment]
Ich fänd eine Kombination der Vorschläge 1 und 2 von @Joshuasony super

**Comment by ZeroPointEnergy** [comment]
@jamoksarita the original issue should be addressed by #82 .
