### ISSUE TITLE
Aufräge/Positionen/Übersicht geleistete Stunden

### ISSUE THREAD

**Issue by jamoksarita** [puzzle/puzzletime#11]
In der Übersicht "Geleistete Stunden" werden alle Stunden inkl. nicht verrechenbaren Stunden angezeigt. Es wäre cool eine Übersicht über das Total der geleisteten Stunden zu haben aber auch ein Übersicht über das total der geleisteten Stunden exkl. den nicht verrechenbaren Stunden.

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
