### ISSUE TITLE
Angabe mehrer Mehrwersteuersätze

### ISSUE THREAD

**Issue by kallies** [puzzle/puzzletime#12]
Als Anwender sollte es möglich sein, Leistungen mit unterschiedlichen MwSt/USt-Steuersätzen zu definiern, um Leistungen mit reduziertem Steuersatz ausweisen zu können bzw. bei Reverse-Charge Rechnungen keine MwSt. auszuweisen. Der reguläre Steuersatz sollte als veränderbarer Standard gesetzt sein.

**Comment by bsantschi** [comment]
Ticket wird Puzzle intern #47523 weiterverfolgt.
