### ISSUE TITLE
Environment variable for x_sendfile_header

### ISSUE THREAD

**Issue by OscarMeier** [puzzle/puzzletime#130]
Currently, the `x_sendfile_header` configuration is hard-coded:

https://github.com/puzzle/puzzletime/blob/d977d5709131189e00d1cfeb6d5e208bb62e7b59/config/environments/production.rb#L44

To deploy your application with NGINX support I have to edit the core and commit my changes. 

What do you think about using an environment variable instead and having 'X-Sendfile' as default?

```ruby
config.action_dispatch.x_sendfile_header = ENV['RAILS_X_SENDFILE_HEADER'] || 'X-Sendfile' # for Apache 
```

**Comment by Kagemaru** [comment]
I agree, I implemented this in commit 34dc613
