### ISSUE TITLE
Spesenbeleg als PDF hochladen

### ISSUE THREAD

**Issue by florianhug** [puzzle/puzzletime#131]
Ich erhalte Spesenbelege als PDF. Es wäre praktisch diese direkt hochladen zu können anstatt einen Screenshot des Dokuments machen zu müssen.

**Comment by bsantschi** [comment]
Gute Idee, Flo. Wir haben das bereits spezifiziert. Umgesetzt haben wir es noch nicht, da es aufwändig wird. Denn wir möchten mehrseitige PDFs unterstützen und müssen diese während der Spesenfreigabe clever darstellen und zudem der Treuhänderin weitergeben. Da das alles sehr Puzzle spezifisch ist, können wir das gerne in unserem OpenProject im Ticket #49088 weiter diskutieren.
