### ISSUE TITLE
Irreführendes Label bei Verpflegungsentschädigung

### ISSUE THREAD

**Issue by plow** [puzzle/puzzletime#132]
Ein privilegierter User kann auf einem Auftrag die Checkbox "Member hat Anrecht auf Verpflegungsentschädigung" betätigen. Dies suggeriert, dass der Member _kein_ Anrecht auf Verpflegungsentschädigung hat, wenn die Checkbox nicht selektiert wird. Tatsächlich steuert man über diese Checkbox nur einen vom Member übersteuerbaren Default (opt-in vs. opt-out).

**Comment by plow** [comment]
PR #133 macht einen Lösungsvorschlag.

**Comment by bsantschi** [comment]
Ähnliche Fehl-Interpretation zeigt sich möglicherweise auch beim Verrechenbarkeits-Flag. Lösungsvorschlag https://github.com/puzzle/puzzletime/pull/134.
