### ISSUE TITLE
Warnung bei Rechnungserstellung auf Auftrag ohne Vertrag

### ISSUE THREAD

**Issue by plow** [puzzle/puzzletime#136]
Auf einem Auftrag ohne hinterlegte Vertragsnummer kann keine Rechnung erstellt werden. Wenn man es dennoch versucht, erscheint die Fehlermeldung erst beim Speichern der Rechnung (nach dem Ausfüllen des Rechnungs-Forms). Ein Warnhinweis oberhalb des Rechnungs-Formulars wäre in diesem Fall nett, damit man das Formular nicht vergebens ausfüllt.

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
