### ISSUE TITLE
Feature: Datum bei überlappenden Einträge

### ISSUE THREAD

**Issue by schlapzz** [puzzle/puzzletime#139]
Erfasst man zwei Einträge welche sich in der Zeit überlappen erscheint ein Hinweis.
Es wäre noch praktisch wenn beim Hinweis auch gleich noch das Datum angezeigt wird unter welchem die Überlappenden Einträge erfasst wurden. Aktuell werden nur die Einträge mit den Arbeitszeiten angezeigt. Die Anzeige des Entsprechenden Tag/Datum würde die Suche nach den überlappenden Einträge ein wenig vereinfachen.

![Inkedchrome_0Emexlb0eZ_LI](https://user-images.githubusercontent.com/69156773/104837177-1fc00400-58b3-11eb-8e54-91dbf03aa2ba.jpg)

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
