### ISSUE TITLE
Feature: Favoritisierbare Projekte für schnelleres Buchen

### ISSUE THREAD

**Issue by PhilipSchmid** [puzzle/puzzletime#140]
Gerade wenn man eigentlich mehrheitlich immer auf die gleichen ~3 Projekte bucht, wäre es sehr hilfreich, wenn man bei der Zeitbuchung-Eingabemaske seine favoritisierten Projekte gleich angezeigt bekommen würde, ohne das man erst danach suchen muss. Dies wäre vor allem dann hilfreich, wenn es mehrere Projekte mit dem gleichen Prefix gibt und man somit nicht einfach die ersten paar Buchstaben eintippen kann, sondern dann bei der Auswahl genau schauen muss, dass man ja das richtige Projekt erwischt.

Um ein Projekt als Favorit zu kennzeichnen zu können, könnte ich mir vorstellen, dass es z.B. rechts neben einem Projekt immer ein Favorit-Star hat (orange eingekreiste Stelle), welchen man jederzeit an- oder abwählen könnte.

![image](https://user-images.githubusercontent.com/5549063/104892118-1649a100-5972-11eb-8730-46edbd502603.png)

Die favoritisierten Projekte werden dann in einer separaten Liste z.B. rechts oder unterhalb des `Buchungsposition`-Feldes angezeigt. Alternativ könnte ich mir vorstellen, dass alle favoritisierten Projekte auch ohne Eingabe direkt beim Klick auf den Drop-Down-Pfeil angezeigt werden.

**Comment by Joshuasony** [comment]
Super Idee! Würde für mich die Zeiterfassung auch erleichtern, besonders eben bei ähnlich lautenden Buchungspositionen. Ein Beispiel bei mir wäre das:
![grafik](https://user-images.githubusercontent.com/7139459/104917675-05118c00-5994-11eb-89bb-8d470c6bb0fc.png)
Die erste Position ist meine, die zweite die von Julian.

Ich stelle es mir ähnlich vor: die favorisierten Projekte erscheinen beim fokussierten Eingabefeld "Buchungsposition" sofort in einer Liste, damit man die schnell auswählen kann (und nicht suchen/filtern muss). Klickt man auf den Stern, verschwindet die Position aus der Liste.

**Comment by bsantschi** [comment]
Hoi zämä, das ist eine super Idee und wurde schon öfters gewünscht. Die Umsetzung scheiterte lediglich am Budget (denn ganz so trivial ist es nicht, einerseits müsste das Such-Widget angepasst werden, andererseits gibt auch die Verwaltung der Favoriten (oder das automatische Erlernen der Favoriten) auch was zu tun. Ich halte es im Backlog.

Josh, geh bitte für eine angenehmere User Experience auf deinen PL/BL zu. Die Buchungspositionen sind ungünstig benennt und könnten innert Sekunden umbenannt werden, so dass du sie leichter findest.

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
