### ISSUE TITLE
Feature: Auslastungsbalken Member auf der Auftragsplanungsübersicht

### ISSUE THREAD

**Issue by severinraez** [puzzle/puzzletime#142]
Mit @chrusu rausgefunden: Via _Planung -> Aufträge_ sieht man nicht, wie die Auslastung der Members ist, man muss ein zweites Fenster mit einer Members-Liste öffnen, um die offene Restkapazität zu sehen. Praktisch wäre ein "Kapazitätsbalken" analog der Members-Listen-Ansicht

**Comment by bsantschi** [comment]
Nebst "Planung -> Aufträge" wäre das auch in der Multi-Auftragssicht "Planung -> Organisationseinheiten -> Aufträge" wertvoll.

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
