### ISSUE TITLE
JSON-APIs um Daten per Script oder ähnliches auslesen zu können.

### ISSUE THREAD

**Issue by chrusu** [puzzle/puzzletime#143]
Gewünschtes Verhalten:
- Um auszurechnen, wieviele StoryPoints das Hitobito-Teams im nächsten Sprint leisten kann, benötige ich folgende Daten um dies auszurechnen. Aktuell trage ich die Daten manuell in ein Excel, was sehr Aufwändig ist.
- Schön wäre es, wenn ich mir ein kleines Script schreiben könnte, welches die benötigten Daten per API ausliest und für mich rechnet ;-)

Gewünschte Endpoints:
- planung eines Members (nach Zeitraum gefiltert)
  - Stunden pro Projekt und Tag
- Leistungen eines Projektes (nach Zeitraum/Member(s) gefiltert)
  - verrechenbar

**Comment by bsantschi** [comment]
Hey Tobi, ich verstehe deinen Wunsch, möchte aber dem "sehr Aufwändig" widersprechen. Wir haben das schon öfters im PL-Gremium besprochen und sind darauf gekommen, dass das Übertragen nicht so aufwändig ist und einem viel Flexibilität ermöglicht. Bitte tausche dich bei Gelegenheit mit anderen PL darüber aus, wie sie es machen. Budget für PuzzleTime Erweiterungen haben wir zur Zeit nur für das nötigste - sprich wenn viele PL das möchten, dann gehen wir natürlich auch das an.

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
