### ISSUE TITLE
Export Memberliste als CSV

### ISSUE THREAD

**Issue by olibrian** [puzzle/puzzletime#174]
Die Liste `employee_master_data`soll als csv exportiert werden können. Das F&A Team braucht immer mal wieder eine Liste mit allen Members (z.b. für Events, Päckli, etc). Anstelle eine eigene Liste zu führen, soll ptime als Master fungieren und die Daten liefern.
Zusätzlich zu den employee_master_data Attributen soll noch die Adresse exportiert werden.

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
