### ISSUE TITLE
QR Code mit Kontaktdaten statt URL

### ISSUE THREAD

**Issue by plow** [puzzle/puzzletime#176]
In der Stammdatenansicht eines Mitarbeitenden (`/employee_master_data/[ID]`) wird ein QR Code angezeigt. An sich ein praktisches Feature, wenn man schnell einen Kontakt aufs Handy übertragen will. Der QR-Code encodiert aber nicht die Kontaktdaten des Mitarbeitenden, sondern eine URL auf ein VCF-File mit ebendiesen. Dieser Umstand wertet das Feature ab, da zu umständlich. Es wäre schön, wenn im QR-Code direkt die Kontaktdaten hinterlegt wären.

PS: Im Puzzle Setup öffnet die URL im QR-Code einen HTTP BasicAuth Dialog, der aber nicht funktioniert, wohl weil PuzzleTime nur noch über SSO zugänglich ist.

**Comment by bsantschi** [comment]
Wir bauen den aktuellen QR Code wie folgt um:

- Daten direkt in QR Code (VCARD)
- nur auf dem Mitarbeiter-Blatt anzeigen

Daten (wie auf den Visitenkarten):
- Vorname Nachname
- Puzzle ITC GmbH
- Mobilenummer
- Festnetznummer
- E-Mailadresse

Ich vermute, dass wir es mit der heutigen rqrcode Library wie folgt umsetzen können:
https://github.com/whomwah/rqrcode/issues/46#issuecomment-1130408104

**Comment by bsantschi** [comment]
Hoi @daniel-illi und @Kagemaru wäre es möglich das Puzzle Logo in der Mitte des QR-Codes einzubauen? Und falls ja, wie hoch wäre der Aufwand etwa?

**Comment by bsantschi** [comment]
Danke für die Einschätzung, Dani. Der Wunsch sieht nun etwas anders aus, ich schliesse das Ticket aber und erstelle ein neues.
