### ISSUE TITLE
screenshots are missing

### ISSUE THREAD

**Issue by felixkrohn** [puzzle/puzzletime#182]
(feedback from a customer looking into time accounting software)

**Comment by bsantschi** [comment]
Lieber @felixkrohn, danke für das Ticket und entschuldige meine späte Antwort. Kannst du mir sagen wo die Screenshots fehlen?

**Comment by felixkrohn** [comment]
Ich glaube das bezog sich auf die Readme/Doku - screenshots sind ein einfacher weg das look&feel abzuschätzen, und Neugierde zu wecken. $Kunde hat sich das readme kurz angesehen und dann die seite geschlossen weil das eben nach "Code" aussieht, nicht nach "einsetzbares Produkt".

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
