### ISSUE TITLE
Authentifizierung bei Member vCard funktioniert nicht mehr

### ISSUE THREAD

**Issue by hupf** [puzzle/puzzletime#191]
Auf der Member Detailseite (z.B. https://time.puzzle.ch/employee_master_data/111) gibt es einen QR Code mit einem Link. Dieser ist dazu da um z.B. auf einem Smartphone geöffnet zu werden. Nach der Anmeldung sollte dann die vCard heruntergeladen bzw. importiert werden können.

Leider scheint Authentifizierung jedoch nicht mehr zu funktionieren. Zum reproduzieren kann eine vCard (z.B. https://time.puzzle.ch/employee_master_data/111.vcf) in einem private Window geöffnet werden und versucht werden einzuloggen. Die Antwort ist stets ein 401.

Funktioniert dies seit der Umstellung auf SSO nicht mehr?

**Comment by bsantschi** [comment]
Danke für den Hinweis, Hupf und entschuldige meine späte Antwort. Das funktioniert tatsächlich seit der Umstellung auf SSO nicht mehr. Wir bauen den QR Code nun so um, dass der QR Code die Daten beinhaltet und nicht mehr auf PuzzleTime verlinkt. Ich erlaube mir daher dieses Ticket zu schliessen und wir tracken den Fortschritt des QR Code Umbaus im Ticket https://github.com/puzzle/puzzletime/issues/176
