### ISSUE TITLE
Postgres Upgrade

### ISSUE THREAD

**Issue by daniel-illi** [puzzle/puzzletime#197]
Puzzletime läuft mit der alten Postgres Version 9.5 welche seit February 11, 2021 EOL ist.

Die Test Suite läuft hingegen mit einem Postgres 11. Das ist gar nicht gut, die Tests sollten zwingend mit derselben Version laufen, wie die produktive Instanz.
Postgres 11 wird aber das letzte Release auch schon	am November 9, 2023 erhalten. Ich denke es macht mehr Sinn, gleich auf Postgres 15/16 zu aktualisieren.

**Comment by bsantschi** [comment]
Wird im Rahmen der Version 2.11 erledigt sein.
