### ISSUE TITLE
Ferienplan Filter nach Organisationseinheit

### ISSUE THREAD

**Issue by olibrian** [puzzle/puzzletime#200]
Der Ferienplan (/vacations) wird bei vielen Members sehr unübersichtlich und gross. Gerne würde ich diese Ansicht nach Organisationseinheit filtern:

![image](https://github.com/puzzle/puzzletime/assets/9592347/7f671edf-355b-4f3a-ab16-9a31c9894122)

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
