### ISSUE TITLE
Alerting when time contract is (becoming) fulfilled

### ISSUE THREAD

**Issue by felixkrohn** [puzzle/puzzletime#213]
When adding a new diary entry in pTime, it would be nice to check how much time is still available on the contract and send alerts to the contract's owner(s) and submitters.

As a consequence of this check I suggest some warnings (by mail or UX):
- mail to the contract's owners when 75% are reached
- mail or UX notification to the time submitter when >= 90% are reached (or less than say 4 hrs remain available)
- (and in parallel as well a mail to the project's owners?)

**Comment by bsantschi** [comment]
Wird im Rahmen des Puzzle internen Tickets #51298 umgesetzt.
