### ISSUE TITLE
Korrekte Interpretation von zweistelligen Jahreszahl

### ISSUE THREAD

**Issue by olibrian** [puzzle/puzzletime#216]
**Ausgangslage**
Wenn die Zeitspanne manuell gewählt wird und als Datum nur eine zweistellige Zahl (1.7.24) eingegeben wird, interpretiert dies Ptime als 01.07.0024. Dies kann zu einer grosse Abfragen führen.

**Gewünschtes Verhalten:**
Bei der Eingabe von zweistelligen Jahreszahlen sollen diese im aktuellen Jahrhundert interpretiert werden.

**Comment by bsantschi** [comment]
Wird im Rahmen des Puzzle internen Tickets #63095 umgesetzt.
