### ISSUE TITLE
RBAC: Social Security Number should only be readable by management

### ISSUE THREAD

**Issue by kallies** [puzzle/puzzletime#23]
Sensitive data like the social security number should only be readable by staff with "is management" flag. Best would be to have a role based access model (i.e. only HR can access this kind of data).

**Comment by bsantschi** [comment]
In Version 2.5 umgesetzt.

**Comment by bsantschi** [comment]
Hoi Lukas, bei uns benötigen die Auftragsverantwortlichen und Personen im Sales-Team die Social/AHV-Nummer anderer Mitarbeiter um Offerten zu stellen. Wir ändern daher die Berechtigung so dass nebst "Management" auch "Auftragsverwantwortliche" (aber nicht "Members") Zugriff auf die Nummern anderer Members haben. Hoffe, das passt auch für dich so.

**Comment by kallies** [comment]
Das ist in Ordnung. Schön wäre eine Dokumentation der Rolle Auftragsverantwortlicher (wann kommt diese zum Tragen, wie wird diese zugewiesen?)
