### ISSUE TITLE
Kommentierung von Mitarbeiterplanungen

### ISSUE THREAD

**Issue by plow** [puzzle/puzzletime#26]
Die Planungsübersicht auf Unternehmensebene gibt die Planungssituation in einem definierten Zeitintervall in Form einer Mitarbeitende/Kalenderwochen-Matrix wieder. In dieser Ansicht wird die potentiell feingranulare Planung eines Mitarbeitenden auf eine prozentuale Auslastung pro Kalenderwoche reduziert. Eine Kommentierung der Planung ist bisher nicht möglich.

Es wäre wünschenswert, Mitarbeiterplanungen mit Notizen und Kommentaren zu versehen (z.B. zu offenen Leads oder potentiellen künftigen Aufträgen). Ein Freitextfeld pro Mitarbeiter würde reichen. Die Kommentare auf Mitarbeiterebene sollten in der Unternehmensplanungs-Sicht als Interpretationshilfe ersichtlich werden.

**Comment by bsantschi** [comment]
Danke für den Input, Simu! @pmurkowsky erarbeitet seitens UX einen Lösungsvorschlag, den wir danach umsetzen werden.

**Comment by bsantschi** [comment]
Wird nicht umgesetzt.
