### ISSUE TITLE
UX Bug kopieren/bearbeiten

### ISSUE THREAD

**Issue by gcomte** [puzzle/puzzletime#28]
Wenn man einen Zeiteintrag kopieren möchte, passiert es oft dass man sich um ein paar Pixel verklickt und dann direkt den originalen Zeiteintrag bearbeitet anstatt wie gewollt dessen Kopie.
Problematisch wird dies dann, wenn man dies nicht bemerkt.

Eine Lösung könnte folgende Punkte beinhalten:

- Link um Kopieren-Icon vergrössern
- Bearbeiten-Link bei den Tools (Kopieren und Löschen) wegnehmen
- Eigenes Icon fürs Bearbeiten eines Eintrags
- Auffällig andere "Kopieren" als "Bearbeiten" Seite.
- ...

**Comment by odaner** [comment]
+1 hat mich auch schon oft genervt, rsp. ich habe anstatt kopiert dann leider editiert...

**Comment by cfasnacht** [comment]
+1 Geht mir genau so.
Die andern Knöpfe finde ich eigentlich ok, eventuell den + Knopf auch noch etwas grösser aber das muss nicht sein.

**Comment by bsantschi** [comment]
Einfachste Variante umgesetzt, bei dem das Bearbeiten nicht mehr hinter den Aktionen Duplizieren und Löschen verlinkt ist.
