### ISSUE TITLE
Navigation ist nicht "sticky"

### ISSUE THREAD

**Issue by odaner** [puzzle/puzzletime#29]
Hallo zusammen. Ich finde es schade, dass die Navigation-Bar im PTime nicht "sticky" ist. Wenn ich irgendwo im PTime nach unten scrolle, und dann aber in ein anderes Menu-Element will, muss ich zuerst nach oben scrollen um navigieren zu können. Das ist imho nicht gerade ein gutes UX-Pattern. 

Ich möchte, dass mir die Navigation / Subnavigation immer angezeigt wird.

**Comment by tobiasosDev** [comment]
Mein Pull-Request wurde angenommen und merged. Sollte also nun gemacht sein.
Hoffe ist so wie gewünscht.

**Comment by odaner** [comment]
wow, danke @tobiasosDev :-D PS: Darf ich fragen wie du auf PuzzleTime gekommen bist?

**Comment by tobiasosDev** [comment]
Ich habe mich bei euch beworben und hat leider nicht geklappt. Aber dabei habe ich mitbekommen das Ihr viele eurer Produkte Open-Source stellt und dies war eine Frage des Interviews da dachte ich löse ich diesen doch gleich.

**Comment by bsantschi** [comment]
In 2.5 umgesetzt.
