### ISSUE TITLE
Mit Tab von Buchungsposition zu Ticket wechseln

### ISSUE THREAD

**Issue by Robin481** [puzzle/puzzletime#34]
Ist (Firefox 65.0.1):
Wenn man eine Buchungsposition mit Enter auswählt und dann Tab drückt öffnet sich das Dropdown-Menü der Buchungsposition wieder.

Soll: 
Wenn man eine Buchungsposition mit Enter auswählt und dann Tab drückt springt man ins Input-Feld "Ticket". Dies gewährleistet den normalen Tab-Workflow welcher im Rest der Ansicht "Arbeitszeit erfassen" möglich ist.

**Comment by hupf** [comment]
Dies ist die Hauptnervigstesache bezüglich Usablitity bei Puzzletime: Es gibt kein Keyboardonly weiterkommen wenn man mal auf der Buchungsposition ist. Und gerade bei der Zeiterfassung wäre das besonders wichtig.

Wahrscheinlich muss die Option `selectOnTab` disabled werden.

**Comment by topaxi** [comment]
Ist ein Bug in selectice, ist upstream gefixed aber wohl noch nicht up to date im gem? https://github.com/selectize/selectize.js/pull/1353

**Comment by Kagemaru** [comment]
Ich habe mir das mal angeschaut.
Wir sind auf selectize.js Version `0.12.6`, der Fix war bei `0.12.5` dabei.
Ich kann das Problem beheben, wenn ich `openOnFocus: false` setze.
Dies möchte ich jedoch noch schnell mit Bruno anschauen, bevor ich es einbaue.

**Comment by bsantschi** [comment]
Danke, Thomas, funktioniert auf Master wieder.

**Comment by topaxi** [comment]
🎉🎉🎉
