### ISSUE TITLE
Feature: Buchungstemplate

### ISSUE THREAD

**Issue by resmo** [puzzle/puzzletime#44]
Es gibt Buchungen, welche man regelmässig, bzw. täglich macht. z.B. Dailys. Damit diese rasch gemacht werden können, wäre es nice, wenn man sowas wie ein Template machen könnte, welches dann am Tag angewendet werden kann. Dabei können die Felder wie in der Buchung verwendet werden, jedoch alle optional. D.h. Zeit könnte z.B. Leer bleiben.

**Comment by bsantschi** [comment]
Die Idee gefällt mir sehr. Hast du dir schon Gedanken gemacht, wo diese Templates im GUI verwaltet und ausgewählt werden sollen? Oder wäre der Ansatz wünschenswert, dass PuzzleTime basierend auf den letzten Einträgen selber Vorschläge macht?

**Comment by resmo** [comment]
Fürs erste würde mir eine einfache Liste, welche ich selber pflegen kann, genügen.
