### ISSUE TITLE
Überschriften überlagen sich beim Scrollen

### ISSUE THREAD

**Issue by kallies** [puzzle/puzzletime#59]
Ist der Bereich unter /plannings/departments/1/multi_orders scrollbar und man scrollt nach unten, so überlagern sich die `<h1 class='h3'>` Überschriften.

![image](https://user-images.githubusercontent.com/482371/61199346-ee72e080-a6dd-11e9-8f6f-9b05386644f1.png)

Getestet mit Firefox 67.0 und Chromium 75 auf Ubuntu 18.04

**Comment by Kagemaru** [comment]
Danke fürs melden, dass sind Nachwehen vom Sticky header.
Wir machen heute Abend ein Nachrelease, wo dieser Change drin ist.

Fixed in 2e61de3ce1567b74f7944ac69518565f13e0ec28
