### ISSUE TITLE
Bug: Parameter per_page der API scheint keinen Effekt zu haben

### ISSUE THREAD

**Issue by severinraez** [puzzle/puzzletime#68]
Rufe ich `/api/v1/employees?per_page=100` auf, kommen trotzdem nur 20 Einträge zurück.

Der Parameter ist hier in der Doku erwähnt: https://github.com/puzzle/puzzletime/blob/master/doc/user/api.md

**Comment by Kagemaru** [comment]
Works on my production?
GET https://time.puzzle.ch/api/v1/employees?per_page=200

Count: 200

**Comment by severinraez** [comment]
Wenn's nun geht ist gut :)
