### ISSUE TITLE
Force SSL in Production

### ISSUE THREAD

**Issue by codez** [puzzle/puzzletime#98]
In `config/environments/production.rb` sollte das Setting `force_ssl` gesetzt werden, damit Cookies und Headers die vollen Sicherheitsvorkehrungen berücksichtigen.

Standardumsetzung mit Umgebungsvariable RAILS_HOST_SSL, welche in den entsprechenden Deployments gesetzt werden muss: 
```ruby
  ssl = %w[true yes 1].include?(ENV['RAILS_HOST_SSL'])
  config.force_ssl = ssl
  config.ssl_options = {
    redirect: { exclude: ->(request) { request.path =~ /healthz/ } }
  }
```

**Comment by Kagemaru** [comment]
Implementiert in commit 09fd609
